CREATE TABLE WHITE (id serial PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE black (id serial PRIMARY KEY, name TEXT NOT NULL, white_id INT REFERENCES white(id));
CREATE TABLE pink (id serial PRIMARY KEY, name TEXT NOT NULL, black_id INT REFERENCES black(id) NOT NULL);
CREATE TABLE brown (id serial PRIMARY KEY, name text NOT NULL);
CREATE TABLE cian (id serial PRIMARY KEY, name text NOT NULL);
CREATE TABLE orange (id serial PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE yellow (id serial PRIMARY KEY, name text NOT NULL, brown_id INT REFERENCES brown(id) NOT NULL, cian_id INT REFERENCES cian(id) NOT NULL, orange_id INT REFERENCES orange(id));
CREATE TABLE green (id serial PRIMARY KEY, name text NOT NULL, green_id INT REFERENCES green(id) NOT NULL, yellow_id INT REFERENCES yellow(id) NOT NULL, black_id INT REFERENCES black(id) NOT NULL);
CREATE TABLE red (id serial PRIMARY KEY, name text NOT NULL, green_id INT REFERENCES green(id), pink_id INT REFERENCES pink(id) NOT NULL);
CREATE TABLE blue (id serial PRIMARY KEY, name text NOT NULL, red_id INT REFERENCES red(id) NOT NULL);
ALTER TABLE white ADD COLUMN blue_id INT REFERENCES blue(id);
